version: '3.8'

services:
  app:
    build: .
    container_name: tuvaloracion-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_URI_INTERNAL=mongodb://mongodb:27017/tuvaloracion
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - APP_DOMAIN=${APP_DOMAIN}
    depends_on:
      - mongodb
    networks:
      - tuvaloracion-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: tuvaloracion-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=tuvaloracion
    volumes:
      - mongodb-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - tuvaloracion-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: tuvaloracion-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - tuvaloracion-network
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local

networks:
  tuvaloracion-network:
    driver: bridge
